import { hash } from 'bcrypt';

enum Gender {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
}

enum Role {
    warAdm = 'warAdm',
    superAdm = 'superAdm',
}

export async function listAdmin() {
    return [
        {
            role: Role.superAdm,
            accountActive: true,
            fullName: 'Jane Aid',
            email: 'janeaid@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.FEMALE,
            dob: new Date('1985-01-01'),
            createdAt: new Date(),
        },
        {
            role: Role.warAdm,
            accountActive: true,
            fullName: 'John Smith',
            email: 'johnsmith@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.MALE,
            dob: new Date('1990-02-02'),
            createdAt: new Date(),
        },
        {
            role: Role.warAdm,
            accountActive: true,
            fullName: 'Tony Stark',
            email: 'tonystark@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.MALE,
            dob: new Date('1970-05-29'),
            createdAt: new Date(),
        },
        {
            role: Role.warAdm,
            accountActive: true,
            fullName: 'Natasha Romanoff',
            email: 'natasharomanoff@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.FEMALE,
            dob: new Date('1984-11-22'),
            createdAt: new Date(),
        },
        {
            role: Role.warAdm,
            accountActive: true,
            fullName: 'Steve Rogers',
            email: 'steverogers@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.MALE,
            dob: new Date('1918-07-04'),
            createdAt: new Date(),
        },
        {
            role: Role.warAdm,
            accountActive: true,
            fullName: 'Bruce Banner',
            email: 'brucebanner@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.MALE,
            dob: new Date('1969-12-18'),
            createdAt: new Date(),
        },
        {
            role: Role.warAdm,
            accountActive: true,
            fullName: 'Wanda Maximoff',
            email: 'wandamaximoff@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.FEMALE,
            dob: new Date('1989-05-10'),
            createdAt: new Date(),
        },
        {
            role: Role.warAdm,
            accountActive: true,
            fullName: 'Peter Parker',
            email: 'peterparker@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.MALE,
            dob: new Date('1998-08-10'),
            createdAt: new Date(),
        },
        {
            role: Role.warAdm,
            accountActive: true,
            fullName: 'Carol Danvers',
            email: 'caroldanvers@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.FEMALE,
            dob: new Date('1969-03-17'),
            createdAt: new Date(),
        },
        {
            role: Role.warAdm,
            accountActive: true,
            fullName: 'T Challa',
            email: 'tchalla@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.MALE,
            dob: new Date('1975-02-16'),
            createdAt: new Date(),
        },
        {
            role: Role.warAdm,
            accountActive: true,
            fullName: 'Scott Lang',
            email: 'scottlang@example.com',
            password: await hash('Mysql123-', 10),
            gender: Gender.MALE,
            dob: new Date('1980-06-08'),
            createdAt: new Date(),
        },
    ];
}
